<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Manish-PC" ignored="0" name="Test" tests="20" failures="2" timestamp="13 Oct 2018 22:12:53 GMT" time="11.372" errors="0">
  <testcase name="NumberFormat" time="0.007" classname="org.testng.ExceptionTimeout"/>
  <testcase name="infiniteloop" time="2.008" classname="org.testng.ExceptionTimeout">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.ExceptionTimeout.infiniteloop() didn&amp;apos;t finish within the time-out 2000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.ExceptionTimeout.infiniteloop() didn't finish within the time-out 2000
at java.io.FileOutputStream.writeBytes(Native Method)
at java.io.FileOutputStream.write(Unknown Source)
at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
at java.io.BufferedOutputStream.flush(Unknown Source)
at java.io.PrintStream.write(Unknown Source)
at sun.nio.cs.StreamEncoder.writeBytes(Unknown Source)
at sun.nio.cs.StreamEncoder.implFlushBuffer(Unknown Source)
at sun.nio.cs.StreamEncoder.flushBuffer(Unknown Source)
at java.io.OutputStreamWriter.flushBuffer(Unknown Source)
at java.io.PrintStream.write(Unknown Source)
at java.io.PrintStream.print(Unknown Source)
at java.io.PrintStream.println(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- infiniteloop -->
  <testcase name="EnterText" time="0.243" classname="org.testng.GroupingTest"/>
  <testcase name="f1" time="0.049" classname="org.testng.GroupingTest"/>
  <testcase name="f2" time="0.002" classname="org.testng.GroupingTest"/>
  <testcase name="f3" time="0.002" classname="org.testng.GroupingTest"/>
  <testcase name="googletitleTest" time="0.077" classname="org.testng.GroupingTest"/>
  <testcase name="Invocationcountmethod" time="0.02" classname="org.testng.InvocationCount"/>
  <testcase name="Invocationcountmethod" time="0.313" classname="org.testng.InvocationCount"/>
  <testcase name="Invocationcountmethod" time="0.005" classname="org.testng.InvocationCount"/>
  <testcase name="Invocationcountmethod" time="0.027" classname="org.testng.InvocationCount"/>
  <testcase name="Invocationcountmethod" time="0.024" classname="org.testng.InvocationCount"/>
  <testcase name="Invocationcountmethod" time="0.006" classname="org.testng.InvocationCount"/>
  <testcase name="Invocationcountmethod" time="0.015" classname="org.testng.InvocationCount"/>
  <testcase name="Invocationcountmethod" time="0.009" classname="org.testng.InvocationCount"/>
  <testcase name="Invocationcountmethod" time="0.062" classname="org.testng.InvocationCount"/>
  <testcase name="Invocationcountmethod" time="0.057" classname="org.testng.InvocationCount"/>
  <testcase name="login" time="0.017" classname="org.testng.testingfeature">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase name="homepage" time="0.0" classname="org.testng.testingfeature">
    <skipped/>
  </testcase> <!-- homepage -->
  <testcase name="f1" time="0.013" classname="org.testng.TestngSequnce"/>
</testsuite> <!-- Test -->
